# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         Catalyst-Controller-PathArgs
version:      0.2
version_from: lib/Catalyst/Controller/PathArgs.pm
installdirs:  site
requires:
    Catalyst::Runtime:             5.7007
    Class::C3:                     0.14
    Test::Simple:                  0.44

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.30
